### ISSUE TITLE
Common operations

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/redshift#18]
I've now generated similar macro code to perform similar administrative operations in Redshift a handful of times:
* vacuum
* analyze
* create external table (Spectrum)
* add/update external table partitions (Spectrum)

In all cases, these are one-off operations that I schedule as separate runs in dbt Cloud, using a separate superuser connection/environment.

I would be interested in adding standardizing and open-sourcing this code, I'm just not sure if:
* the redshift package is the right place
* my approach to Spectrum matters is too hacky, though this is largely because Redshift/Spectrum's approach to external data is (a) hacky and (b) a bit of an anti-pattern in an ELT stack
* the (currently undocumented) syntax around operations is sufficiently stable or will be backwards compatible in future releases

**Comment by dcereijodo** [comment]
All this sounds very reasonable and an interesting enhancement for the package. I am curious why there hasn't been more activity in this issue.

**Comment by drewbanin** [comment]
@dcereijodo would you be interested in submitting a PR for any of the functionality described here? I agree that these are compelling topics -- we'd happily accept contributions for any of them!

@jtcohen6 has in fact already made some great progress on the external table / partition front. This isn't _totally_ ready for primetime yet, but it's pretty close: https://github.com/fishtown-analytics/dbt-external-tables

If you're not interested in contributing code, we'd also welcome any thoughts you have on these topics. Which of these macros would be most helpful to you? How would you like them to work? Do you have any noteworthy constraints that are worth considering when implementing code for this functionality?

**Comment by dcereijodo** [comment]
The external tables stuff is what caught my attention actually. I have been working with external tables in RS for a while and we have developed some helpers in this field that might be interesting to contribute somehow. However, what we have is very similar to what @jtcohen6 did in https://github.com/fishtown-analytics/dbt-external-tables (which looks great BTW). We did follow a slightly different approach, so I will write my thoughts in an issue there in the `dbt-external-tables` project.

**Comment by davehowell** [comment]
## vacuum & analyze
I think Redshift is totally the right package for vacuum & analyze. They don't apply to Snowflake or Bigquery or the other adapters apart from maybe Postgres. 

I would love to see how you are doing that with dbt. I have seen examples in post_hook but that seems too often, and I would also like to maintain my landing tables (dbt sources) that aren't owned by dbt, but are sourced by it.

My current approach is to use AWS Lambda to manage this maintenance, but it feels a bit out-of-band, I'd much rather use a dbt job for it. 

My approach is to fetch a list of candidate tables, order them by size ascending, and only vacuum them if they are over an unsorted threshold, and analyze them if they are vacuumed or if the stats_off is above a threshold. I check the lambda ctx and if it is near to timing out (15 minutes) I exit and run again.

**Get the candidate list**
```
SELECT
			"schema", 
			"table", 
			COALESCE("unsorted", 0::float) as unsorted,
			COALESCE("stats_off", 0::float) as statsoff
		FROM svv_table_info
		WHERE 1=1
		AND ( unsorted > ? OR stats_off > ? )
		AND schema in (?)
		ORDER BY SIZE ASC;
```

**Optionally vacuum / analyse**
_Yes Redshift supports the alias "analyse" :)_
```go
	var sqls []string
	for _, st := range sickTables {

		if st.Unsorted >= config.MinUnsorted {
			sqls = append(sqls, fmt.Sprintf("VACUUM FULL %s.%s TO 99 PERCENT;", st.Schema, st.Table))
		} else {
			log.Printf("Skipping vacuum on %s.%s", st.Schema, st.Table)
		}
		if st.StatsOff >= config.MinStatsOff {
			sqls = append(sqls, fmt.Sprintf("ANALYSE VERBOSE %s.%s;", st.Schema, st.Table))
		} else {
			log.Printf("Skipping analyse on %s.%s", st.Schema, st.Table)
		}

	}
```
This is conceptually similar to building up a run queue, as you've done here https://github.com/fishtown-analytics/dbt-external-tables/blob/master/macros/external/stage_external_sources.sql#L17

I wouldn't have the hassle of Lambda's 15 minute timeout if using dbt. It would also be nice to see the vacuum / analyze logging in dbt cloud similar to the logging for running normal models.

**Comment by clrcrl** [comment]
Hey @davehowell -- check out the `redshift_maintenance` (operation)[https://github.com/fishtown-analytics/redshift#redshift_maintenance_operation-source] that we've already added to this package.

We also now have a separate [external tables](https://github.com/fishtown-analytics/dbt-external-tables) package.

I'm going to close this issue now -- sorry for any confusion!
